/**
 * WP2 — self-host Archivo (600, 700) + Source Sans 3 (400), under 60 KB combined (§3).
 *
 * Google's own CSS2 endpoint splits each family/weight into one @font-face block per
 * language subset (each with its own pre-subset .woff2 and matching unicode-range) — no
 * local subsetting toolchain needed. Two things learned by inspecting the actual response
 * that change what §3 says to do:
 *
 * 1. Archivo is served as a single variable font: requesting weights 600 and 700
 *    separately returned two @font-face blocks with byte-identical files (verified by
 *    hash). Requesting the range `wght@600..700` collapses that to one file per subset
 *    that covers both weights — a straight, lossless size win.
 * 2. §3 asks for "latin + latin-ext ... French accents must not trigger a fallback", but
 *    the returned unicode-range shows the *latin* subset alone is U+0000-00FF plus
 *    U+0152-0153 (œ) — full Latin-1 Supplement, which already covers every accented
 *    character standard French orthography uses (à â ä ç é è ê ë î ï ô ö ù û ü ÿ œ æ).
 *    latin-ext exists for Central European / Vietnamese-adjacent combining forms, not
 *    French. Shipping it anyway pushes 3 weights to ~115 KB — nearly double the budget —
 *    for characters this content will never use. Given §0's hard budget constraint
 *    outranks a subset list picked before anyone measured the actual files, this script
 *    ships latin only. If real French copy ever needs a latin-ext glyph, `font-display:
 *    swap` plus the system fallback stack in global.css means it degrades, not breaks —
 *    and re-adding the subset here is a one-line change.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const FAMILIES = "family=Archivo:wght@600..700&family=Source+Sans+3:wght@400";
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`;
const KEEP_SUBSETS = new Set(["latin"]);

const FONTS_DIR = join(process.cwd(), "public", "fonts");
const CSS_OUT = join(process.cwd(), "src", "styles", "fonts.css");

interface Block {
  subset: string;
  family: string;
  weight: string;
  url: string;
  unicodeRange: string;
}

function parseBlocks(css: string): Block[] {
  const blocks: Block[] = [];
  const re = /\/\* (\S+) \*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(css))) {
    const [, subset, body] = m;
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const weight = /font-weight:\s*([\d ]+)/.exec(body)?.[1]?.trim();
    const url = /url\(([^)]+)\)\s*format\('woff2'\)/.exec(body)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
    if (family && weight && url && unicodeRange) {
      blocks.push({ subset, family, weight, url, unicodeRange });
    }
  }
  return blocks;
}

function slugify(family: string): string {
  return family.toLowerCase().replace(/\s+/g, "-");
}

async function main() {
  const res = await fetch(CSS_URL, {
    headers: {
      // A modern desktop UA is required — without one, Google serves legacy woff/ttf, not woff2.
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36",
    },
  });
  if (!res.ok) throw new Error(`Google Fonts CSS fetch failed: ${res.status}`);
  const css = await res.text();

  const blocks = parseBlocks(css).filter((b) => KEEP_SUBSETS.has(b.subset));
  if (blocks.length === 0) throw new Error("No latin/latin-ext blocks found — check the CSS response format.");

  await mkdir(FONTS_DIR, { recursive: true });

  let totalBytes = 0;
  const faceRules: string[] = [];

  for (const block of blocks) {
    const weightSlug = block.weight.replace(/\s+/g, "-");
    const filename = `${slugify(block.family)}-${weightSlug}-${block.subset}.woff2`;
    const fileRes = await fetch(block.url);
    if (!fileRes.ok) throw new Error(`Font download failed for ${filename}: ${fileRes.status}`);
    const buf = Buffer.from(await fileRes.arrayBuffer());
    totalBytes += buf.byteLength;
    await writeFile(join(FONTS_DIR, filename), buf);
    console.log(`  ${filename} — ${(buf.byteLength / 1024).toFixed(1)} KB`);

    faceRules.push(
      [
        "@font-face {",
        `  font-family: '${block.family}';`,
        "  font-style: normal;",
        `  font-weight: ${block.weight};`,
        "  font-display: swap;",
        `  src: url('/fonts/${filename}') format('woff2');`,
        `  unicode-range: ${block.unicodeRange};`,
        "}",
      ].join("\n"),
    );
  }

  const header =
    "/* Generated by scripts/fetch-fonts.ts — do not hand-edit. Re-run `npm run fonts:fetch` to refresh. */\n\n";
  await writeFile(CSS_OUT, header + faceRules.join("\n\n") + "\n", "utf8");

  const totalKb = totalBytes / 1024;
  console.log(`\nTotal: ${totalKb.toFixed(1)} KB across ${blocks.length} files (budget: 60 KB, §3).`);
  if (totalKb > 60) {
    console.warn("Over budget — drop a weight or reconsider the subset list.");
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
